### ISSUE TITLE
Suporte

### ISSUE THREAD

**Issue by Birusca** [Floodeer/UltraGadgets#2]
Olá, eu vi o seu plugin através de um video do AbsintoJ, e me apaixonei por ele de uma forma que você não imagina, você tem o melhor plugin de gadget do mundo, e infelizmente não funcionou no meu servidor, e eu não me conformo com isto, peço que me de um suporte para corrigir o mesmo ou tentar arrumar o erro, nem que precise pagar, eu pago! Só preciso dele, por favor!

**Comment by Birusca** [comment]
Servidor 1.8

**Comment by Floodeer** [comment]
Eu removi o suporte da versão 1.8 porque estou usando recursos que só funcionam em servidores 1.9+, existe uma versão mais antiga que suporta 1.8 mas não é estável - http://www.nightcrawl.net/resources/ultragadgets.7/updates

**Comment by Birusca** [comment]
Esta versão do link já é a 1.8 ? Vou testar cara. Obrigado! Caso não funcione, ou tenha algum erro, voce daria a permissão para meu dev corrigir o erro ?

**Comment by Floodeer** [comment]
Você não vai encontrar o código completo da versão 1.8, só se voltar no histórico do GitHub que vai encontrar algumas edições -- mas, pode editar, se tiver problemas fique avontade para passar para outros desenvolvedores adicionar o suporte para 1.8, avise-os precisará de um pouco mais de conhecimento do Protocolo porque fazendo isso você irá quebrar alguns sistemas que são só pra 1.9. 

Vou ver a opção de adicionar o suporte pra 1.8 em uma versão estável.
